-- name: UpsertIngredient :one
-- Matching is by normalized_name (generated by the database), so "Dipirona Sódica",
-- "dipirona sodica" and "dipirona  sódica" all land on the same row. The DO UPDATE
-- is a no-op that exists only to make the statement return the id in both cases.
INSERT INTO active_ingredients (name)
VALUES ($1)
ON CONFLICT (normalized_name)
    DO UPDATE SET name = active_ingredients.name
RETURNING id;

-- name: LinkDrugIngredient :exec
INSERT INTO drug_ingredients (drug_id, ingredient_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING;

-- name: DeleteDrugIngredientsNotIn :exec
-- Removes the links of a drug that are not in the new list of ingredients.
DELETE
FROM drug_ingredients
WHERE drug_id = @drug_id
  AND NOT (ingredient_id = ANY (@ingredient_ids::BIGINT[]));

-- name: ListIngredientsByDrugID :many
SELECT ai.id, ai.name
FROM drug_ingredients AS di
         JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
WHERE di.drug_id = $1
ORDER BY ai.name;

-- name: ListDrugsByEANs :many
-- Resolves the scanned barcodes into drugs, with their active ingredients.
SELECT pe.ean,
       d.id AS drug_id,
       d.brand_name,
       d.manufacturer,
       COALESCE((SELECT array_agg(ai.name ORDER BY ai.name)
                 FROM drug_ingredients AS di
                          JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
                 WHERE di.drug_id = d.id), '{}')::TEXT[] AS active_ingredients
FROM package_eans AS pe
         JOIN packages AS p ON p.id = pe.package_id
         JOIN drugs AS d ON d.id = p.drug_id
WHERE pe.ean = ANY (@eans::TEXT[]);

-- name: SearchIngredients :many
-- Feeds the name suggestions of the interaction rule form. Matching is on
-- normalized_name, so typing "acido" finds "ácido acetilsalicílico", and the
-- trigram index of 000011 is what keeps it fast over thousands of rows.
SELECT ai.id,
       ai.name,
       (SELECT count(*) FROM drug_ingredients AS di WHERE di.ingredient_id = ai.id) AS drugs
FROM active_ingredients AS ai
WHERE @q::TEXT = ''
   OR ai.normalized_name LIKE '%' || normalize_ingredient_name(@q) || '%'
ORDER BY ai.name
LIMIT $1;
