// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/drugs": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Lista remédios (paginado)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Itens por página (padrão 20, máx 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Quantos itens pular (padrão 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/listResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/ListDrugsRow"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid limit / invalid offset",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Cadastra um remédio",
                "parameters": [
                    {
                        "description": "Dados do remédio",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createDrugRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/idResponse"
                        }
                    },
                    "400": {
                        "description": "json inválido ou campo obrigatório faltando",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "registration_number already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drugs/ean/{ean}": {
            "get": {
                "description": "Retorna os dados do remédio e o resumo da bula a partir do código de barras da caixa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Busca a bula simplificada pelo EAN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código EAN da embalagem",
                        "name": "ean",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetSummaryByEANRow"
                        }
                    },
                    "400": {
                        "description": "ean is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "ean not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/drugs/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Atualiza um remédio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do remédio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do remédio",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createDrugRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id ou json inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "drug not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "registration_number already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "drugs"
                ],
                "summary": "Remove um remédio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do remédio",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "drug not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/packages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "Lista embalagens (paginado)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Itens por página (padrão 20, máx 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Quantos itens pular (padrão 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/listResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/ListPackagesRow"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid limit / invalid offset",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Uma embalagem pode ter vários EANs (ex.: código antigo e novo convivendo na prateleira).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "Cadastra uma embalagem (apresentação) de um remédio",
                "parameters": [
                    {
                        "description": "Dados da embalagem",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createPackageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/idResponse"
                        }
                    },
                    "400": {
                        "description": "json inválido ou campo obrigatório faltando",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "drug not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "ean ou presentation_registration já cadastrado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/packages/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "Busca uma embalagem pelo ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da embalagem",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetPackageByIdRow"
                        }
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "package not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "packages"
                ],
                "summary": "Atualiza uma embalagem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da embalagem",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados da embalagem",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/updatePackageRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id ou json inválido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "package not found / drug not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "ean ou presentation_registration já cadastrado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "packages"
                ],
                "summary": "Remove uma embalagem",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da embalagem",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "package not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/summaries": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "summaries"
                ],
                "summary": "Lista bulas simplificadas (paginado)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Itens por página (padrão 20, máx 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Quantos itens pular (padrão 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/listResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/ListSummariesRow"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid limit / invalid offset",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "summaries"
                ],
                "summary": "Cadastra a bula simplificada de um remédio",
                "parameters": [
                    {
                        "description": "Resumo da bula",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/createSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/idResponse"
                        }
                    },
                    "400": {
                        "description": "json inválido ou campo obrigatório faltando",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "drug not found for this drug_id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "this drug already has a summary",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/summaries/drug/{drugID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "summaries"
                ],
                "summary": "Busca a bula simplificada de um remédio",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do remédio",
                        "name": "drugID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetSummaryByDrugIDRow"
                        }
                    },
                    "400": {
                        "description": "invalid drug id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "summary not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/summaries/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "summaries"
                ],
                "summary": "Busca uma bula simplificada pelo ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do resumo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/GetSummaryByIDRow"
                        }
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "summary not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "summaries"
                ],
                "summary": "Atualiza uma bula simplificada",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do resumo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Resumo da bula",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/updateSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id ou json inválido / campo obrigatório faltando",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "summary not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "summaries"
                ],
                "summary": "Remove uma bula simplificada",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do resumo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "summary not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/summaries/{id}/review": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "summaries"
                ],
                "summary": "Marca uma bula simplificada como revisada",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do resumo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quem revisou",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/reviewSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "id ou json inválido / reviewed_by is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "summary not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GetPackageByIdRow": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "eans": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "presentation_registration": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "GetSummaryByDrugIDRow": {
            "type": "object",
            "properties": {
                "adverse_effects": {
                    "type": "string"
                },
                "contraindications": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "drug_interactions": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "leaflet_expedient": {
                    "type": "string"
                },
                "leaflet_published_at": {
                    "type": "string"
                },
                "mechanism_of_action": {
                    "type": "string"
                },
                "missed_dose": {
                    "type": "string"
                },
                "posology": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "side_effects": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "warnings": {
                    "type": "string"
                },
                "what_is_it_for": {
                    "type": "string"
                },
                "when_to_seek_help": {
                    "type": "string"
                }
            }
        },
        "GetSummaryByEANRow": {
            "type": "object",
            "properties": {
                "active_ingredient": {
                    "type": "string"
                },
                "adverse_effects": {
                    "type": "string"
                },
                "brand_name": {
                    "type": "string"
                },
                "contraindications": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "drug_interactions": {
                    "type": "string"
                },
                "ean": {
                    "type": "string"
                },
                "leaflet_expedient": {
                    "type": "string"
                },
                "leaflet_published_at": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "mechanism_of_action": {
                    "type": "string"
                },
                "missed_dose": {
                    "type": "string"
                },
                "posology": {
                    "type": "string"
                },
                "presentation_registration": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                },
                "side_effects": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "warnings": {
                    "type": "string"
                },
                "what_is_it_for": {
                    "type": "string"
                },
                "when_to_seek_help": {
                    "type": "string"
                }
            }
        },
        "GetSummaryByIDRow": {
            "type": "object",
            "properties": {
                "adverse_effects": {
                    "type": "string"
                },
                "contraindications": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "drug_interactions": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "leaflet_expedient": {
                    "type": "string"
                },
                "leaflet_published_at": {
                    "type": "string"
                },
                "mechanism_of_action": {
                    "type": "string"
                },
                "missed_dose": {
                    "type": "string"
                },
                "posology": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "side_effects": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "warnings": {
                    "type": "string"
                },
                "what_is_it_for": {
                    "type": "string"
                },
                "when_to_seek_help": {
                    "type": "string"
                }
            }
        },
        "ListDrugsRow": {
            "type": "object",
            "properties": {
                "active_ingredient": {
                    "type": "string"
                },
                "brand_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "ListPackagesRow": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "eans": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "presentation_registration": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "ListSummariesRow": {
            "type": "object",
            "properties": {
                "active_ingredient": {
                    "type": "string"
                },
                "brand_name": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "leaflet_expedient": {
                    "type": "string"
                },
                "leaflet_published_at": {
                    "type": "string"
                },
                "reviewed_at": {
                    "type": "string"
                },
                "reviewed_by": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "what_is_it_for": {
                    "type": "string"
                }
            }
        },
        "createDrugRequest": {
            "type": "object",
            "properties": {
                "active_ingredient": {
                    "type": "string"
                },
                "brand_name": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "registration_number": {
                    "type": "string"
                }
            }
        },
        "createPackageRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "400 mg, caixa com 20 cápsulas"
                },
                "eans": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "7891058001155",
                        "7891058017392"
                    ]
                },
                "presentation_registration": {
                    "type": "string",
                    "example": "1234567890014"
                },
                "registration_number": {
                    "type": "string",
                    "example": "1234567890123"
                }
            }
        },
        "createSummaryRequest": {
            "type": "object",
            "properties": {
                "adverse_effects": {
                    "type": "string"
                },
                "contraindications": {
                    "type": "string"
                },
                "drug_id": {
                    "type": "integer"
                },
                "drug_interactions": {
                    "type": "string"
                },
                "leaflet_expedient": {
                    "description": "Versão da bula oficial que foi resumida",
                    "type": "string",
                    "example": "0123456/24-5"
                },
                "leaflet_published_at": {
                    "type": "string",
                    "format": "date",
                    "example": "2024-05-31"
                },
                "mechanism_of_action": {
                    "type": "string"
                },
                "missed_dose": {
                    "type": "string"
                },
                "posology": {
                    "type": "string"
                },
                "side_effects": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "warnings": {
                    "type": "string"
                },
                "what_is_it_for": {
                    "type": "string"
                },
                "when_to_seek_help": {
                    "type": "string"
                }
            }
        },
        "idResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "listResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "reviewSummaryRequest": {
            "type": "object",
            "properties": {
                "reviewed_by": {
                    "type": "string"
                }
            }
        },
        "updatePackageRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "400 mg, caixa com 20 cápsulas"
                },
                "drug_id": {
                    "type": "integer",
                    "example": 1
                },
                "eans": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "7891058001155",
                        "7891058017392"
                    ]
                },
                "presentation_registration": {
                    "type": "string",
                    "example": "1234567890014"
                }
            }
        },
        "updateSummaryRequest": {
            "type": "object",
            "properties": {
                "adverse_effects": {
                    "type": "string"
                },
                "contraindications": {
                    "type": "string"
                },
                "drug_interactions": {
                    "type": "string"
                },
                "leaflet_expedient": {
                    "description": "Versão da bula oficial que foi resumida",
                    "type": "string",
                    "example": "0123456/24-5"
                },
                "leaflet_published_at": {
                    "type": "string",
                    "format": "date",
                    "example": "2024-05-31"
                },
                "mechanism_of_action": {
                    "type": "string"
                },
                "missed_dose": {
                    "type": "string"
                },
                "posology": {
                    "type": "string"
                },
                "side_effects": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "storage": {
                    "type": "string"
                },
                "warnings": {
                    "type": "string"
                },
                "what_is_it_for": {
                    "type": "string"
                },
                "when_to_seek_help": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PharmaCode API",
	Description:      "API que lê o código da caixa do remédio e retorna a bula simplificada.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
