// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drugs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDrug = `-- name: CreateDrug :one
INSERT INTO drugs (registration_number, brand_name, manufacturer)
VALUES ($1, $2, $3) RETURNING id
`

type CreateDrugParams struct {
	RegistrationNumber string      `json:"registration_number"`
	BrandName          pgtype.Text `json:"brand_name"`
	Manufacturer       string      `json:"manufacturer"`
}

// The active ingredients are not here: they live in drug_ingredients and are
// written right after this, inside the same transaction.
func (q *Queries) CreateDrug(ctx context.Context, arg CreateDrugParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDrug, arg.RegistrationNumber, arg.BrandName, arg.Manufacturer)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteDrug = `-- name: DeleteDrug :execrows
DELETE
FROM drugs
WHERE id = $1
`

func (q *Queries) DeleteDrug(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDrug, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDrugByEAN = `-- name: GetDrugByEAN :one
SELECT pe.ean,
       d.id,
       d.registration_number,
       d.brand_name,
       COALESCE((SELECT array_agg(ai.name ORDER BY ai.name)
                 FROM drug_ingredients AS di
                          JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
                 WHERE di.drug_id = d.id), '{}')::TEXT[] AS active_ingredients,
       d.manufacturer,
       d.updated_at,
       d.created_at
FROM package_eans AS pe
         INNER JOIN packages AS p
                    ON p.id = pe.package_id
         INNER JOIN drugs AS d
                    ON d.id = p.drug_id
WHERE pe.ean = $1
`

type GetDrugByEANRow struct {
	Ean                string             `json:"ean"`
	ID                 int64              `json:"id"`
	RegistrationNumber string             `json:"registration_number"`
	BrandName          pgtype.Text        `json:"brand_name"`
	ActiveIngredients  []string           `json:"active_ingredients"`
	Manufacturer       string             `json:"manufacturer"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDrugByEAN(ctx context.Context, ean string) (GetDrugByEANRow, error) {
	row := q.db.QueryRow(ctx, getDrugByEAN, ean)
	var i GetDrugByEANRow
	err := row.Scan(
		&i.Ean,
		&i.ID,
		&i.RegistrationNumber,
		&i.BrandName,
		&i.ActiveIngredients,
		&i.Manufacturer,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDrugByID = `-- name: GetDrugByID :one
SELECT d.id,
       d.registration_number,
       d.brand_name,
       COALESCE((SELECT array_agg(ai.name ORDER BY ai.name)
                 FROM drug_ingredients AS di
                          JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
                 WHERE di.drug_id = d.id), '{}')::TEXT[] AS active_ingredients,
       d.manufacturer,
       d.updated_at
FROM drugs AS d
WHERE d.id = $1
`

type GetDrugByIDRow struct {
	ID                 int64              `json:"id"`
	RegistrationNumber string             `json:"registration_number"`
	BrandName          pgtype.Text        `json:"brand_name"`
	ActiveIngredients  []string           `json:"active_ingredients"`
	Manufacturer       string             `json:"manufacturer"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Used when a form opens already pointing at a drug: the picker only has the
// id, and loading the whole list to find the name is what this change removes.
func (q *Queries) GetDrugByID(ctx context.Context, id int64) (GetDrugByIDRow, error) {
	row := q.db.QueryRow(ctx, getDrugByID, id)
	var i GetDrugByIDRow
	err := row.Scan(
		&i.ID,
		&i.RegistrationNumber,
		&i.BrandName,
		&i.ActiveIngredients,
		&i.Manufacturer,
		&i.UpdatedAt,
	)
	return i, err
}

const getSummaryByEAN = `-- name: GetSummaryByEAN :one
SELECT pe.ean,
       p.description,
       p.presentation_registration,
       d.registration_number,
       d.brand_name,
       COALESCE((SELECT array_agg(ai.name ORDER BY ai.name)
                 FROM drug_ingredients AS di
                          JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
                 WHERE di.drug_id = d.id), '{}')::TEXT[] AS active_ingredients,
       d.manufacturer,
       s.what_is_it_for,
       s.posology,
       s.missed_dose,
       s.warnings,
       s.adverse_effects,
       s.drug_interactions,
       s.contraindications,
       s.side_effects,
       s.when_to_seek_help,
       s.mechanism_of_action,
       s.storage,
       s.source_url,
       s.leaflet_expedient,
       s.leaflet_published_at
FROM package_eans AS pe
         INNER JOIN packages AS p
                    ON p.id = pe.package_id
         INNER JOIN drugs AS d
                    ON d.id = p.drug_id
         LEFT JOIN summaries AS s
                   ON d.id = s.drug_id AND s.reviewed_at IS NOT NULL
WHERE pe.ean = $1
`

type GetSummaryByEANRow struct {
	Ean                      string      `json:"ean"`
	Description              string      `json:"description"`
	PresentationRegistration pgtype.Text `json:"presentation_registration"`
	RegistrationNumber       string      `json:"registration_number"`
	BrandName                pgtype.Text `json:"brand_name"`
	ActiveIngredients        []string    `json:"active_ingredients"`
	Manufacturer             string      `json:"manufacturer"`
	WhatIsItFor              pgtype.Text `json:"what_is_it_for"`
	Posology                 pgtype.Text `json:"posology"`
	MissedDose               pgtype.Text `json:"missed_dose"`
	Warnings                 pgtype.Text `json:"warnings"`
	AdverseEffects           pgtype.Text `json:"adverse_effects"`
	DrugInteractions         pgtype.Text `json:"drug_interactions"`
	Contraindications        pgtype.Text `json:"contraindications"`
	SideEffects              pgtype.Text `json:"side_effects"`
	WhenToSeekHelp           pgtype.Text `json:"when_to_seek_help"`
	MechanismOfAction        pgtype.Text `json:"mechanism_of_action"`
	Storage                  pgtype.Text `json:"storage"`
	SourceUrl                pgtype.Text `json:"source_url"`
	LeafletExpedient         pgtype.Text `json:"leaflet_expedient"`
	LeafletPublishedAt       pgtype.Date `json:"leaflet_published_at"`
}

func (q *Queries) GetSummaryByEAN(ctx context.Context, ean string) (GetSummaryByEANRow, error) {
	row := q.db.QueryRow(ctx, getSummaryByEAN, ean)
	var i GetSummaryByEANRow
	err := row.Scan(
		&i.Ean,
		&i.Description,
		&i.PresentationRegistration,
		&i.RegistrationNumber,
		&i.BrandName,
		&i.ActiveIngredients,
		&i.Manufacturer,
		&i.WhatIsItFor,
		&i.Posology,
		&i.MissedDose,
		&i.Warnings,
		&i.AdverseEffects,
		&i.DrugInteractions,
		&i.Contraindications,
		&i.SideEffects,
		&i.WhenToSeekHelp,
		&i.MechanismOfAction,
		&i.Storage,
		&i.SourceUrl,
		&i.LeafletExpedient,
		&i.LeafletPublishedAt,
	)
	return i, err
}

const listDrugs = `-- name: ListDrugs :many
SELECT d.id,
       d.registration_number,
       d.brand_name,
       COALESCE((SELECT array_agg(ai.name ORDER BY ai.name)
                 FROM drug_ingredients AS di
                          JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
                 WHERE di.drug_id = d.id), '{}')::TEXT[] AS active_ingredients,
       d.manufacturer,
       d.updated_at
FROM drugs AS d
WHERE $3::TEXT = ''
   OR d.id IN (SELECT dd.id
               FROM drugs AS dd
               WHERE normalize_ingredient_name(
                             COALESCE(dd.brand_name, '') || ' ' || dd.manufacturer || ' ' ||
                             dd.registration_number
                     ) LIKE '%' || normalize_ingredient_name($3) || '%'
               UNION
               SELECT di.drug_id
               FROM drug_ingredients AS di
                        JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
               WHERE ai.normalized_name LIKE '%' || normalize_ingredient_name($3) || '%')
ORDER BY d.brand_name NULLS FIRST LIMIT $1
OFFSET $2
`

type ListDrugsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Q      string `json:"q"`
}

type ListDrugsRow struct {
	ID                 int64              `json:"id"`
	RegistrationNumber string             `json:"registration_number"`
	BrandName          pgtype.Text        `json:"brand_name"`
	ActiveIngredients  []string           `json:"active_ingredients"`
	Manufacturer       string             `json:"manufacturer"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// @q is the search box of the panel: it matches the brand name, the company,
// the registration number and the active ingredients, ignoring case and accents
// (normalize_ingredient_name does that). An empty @q lists everything.
//
// The search is written as IN (... UNION ...) and not as a plain OR because the
// OR makes the planner give up on the trigram indexes of 000011 and read the
// whole table: 600 ms against the Anvisa base instead of under 10.
func (q *Queries) ListDrugs(ctx context.Context, arg ListDrugsParams) ([]ListDrugsRow, error) {
	rows, err := q.db.Query(ctx, listDrugs, arg.Limit, arg.Offset, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDrugsRow
	for rows.Next() {
		var i ListDrugsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationNumber,
			&i.BrandName,
			&i.ActiveIngredients,
			&i.Manufacturer,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrug = `-- name: UpdateDrug :execrows
UPDATE drugs
SET registration_number = $2,
    brand_name          = $3,
    manufacturer        = $4,
    updated_at          = NOW()
WHERE id = $1
`

type UpdateDrugParams struct {
	ID                 int64       `json:"id"`
	RegistrationNumber string      `json:"registration_number"`
	BrandName          pgtype.Text `json:"brand_name"`
	Manufacturer       string      `json:"manufacturer"`
}

func (q *Queries) UpdateDrug(ctx context.Context, arg UpdateDrugParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDrug,
		arg.ID,
		arg.RegistrationNumber,
		arg.BrandName,
		arg.Manufacturer,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
