// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drugs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDrugByEAN = `-- name: GetDrugByEAN :one
SELECT p.ean,
       d.registration_number,
       d.brand_name,
       d.active_ingredient,
       d.manufacturer,
       p.description
FROM drugs AS d
         INNER JOIN packages AS p
                    ON d.id = p.drug_id
WHERE p.ean = $1
`

type GetDrugByEANRow struct {
	Ean                string
	RegistrationNumber string
	BrandName          pgtype.Text
	ActiveIngredient   string
	Manufacturer       string
	Description        string
}

func (q *Queries) GetDrugByEAN(ctx context.Context, ean string) (GetDrugByEANRow, error) {
	row := q.db.QueryRow(ctx, getDrugByEAN, ean)
	var i GetDrugByEANRow
	err := row.Scan(
		&i.Ean,
		&i.RegistrationNumber,
		&i.BrandName,
		&i.ActiveIngredient,
		&i.Manufacturer,
		&i.Description,
	)
	return i, err
}
