// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDrugIDByRegistration = `-- name: GetDrugIDByRegistration :one
SELECT id
FROM drugs
WHERE registration_number = $1
`

func (q *Queries) GetDrugIDByRegistration(ctx context.Context, registrationNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, getDrugIDByRegistration, registrationNumber)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertDrug = `-- name: UpsertDrug :one

INSERT INTO drugs (registration_number, brand_name, active_ingredient, manufacturer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (registration_number)
    DO UPDATE SET brand_name        = EXCLUDED.brand_name,
                  active_ingredient = EXCLUDED.active_ingredient,
                  manufacturer      = EXCLUDED.manufacturer,
                  updated_at        = NOW()
RETURNING id, (xmax = 0) AS created
`

type UpsertDrugParams struct {
	RegistrationNumber string      `json:"registration_number"`
	BrandName          pgtype.Text `json:"brand_name"`
	ActiveIngredient   string      `json:"active_ingredient"`
	Manufacturer       string      `json:"manufacturer"`
}

type UpsertDrugRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// Queries used by the spreadsheet import. They upsert by the natural keys
// (registration number, presentation registration, EAN) so importing the same
// file twice updates the rows instead of duplicating them.
// "(xmax = 0) AS created" is the Postgres trick to tell an INSERT from an UPDATE.
func (q *Queries) UpsertDrug(ctx context.Context, arg UpsertDrugParams) (UpsertDrugRow, error) {
	row := q.db.QueryRow(ctx, upsertDrug,
		arg.RegistrationNumber,
		arg.BrandName,
		arg.ActiveIngredient,
		arg.Manufacturer,
	)
	var i UpsertDrugRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertPackage = `-- name: UpsertPackage :one
INSERT INTO packages (drug_id, description, presentation_registration)
VALUES ($1, $2, $3)
ON CONFLICT (presentation_registration)
    DO UPDATE SET drug_id     = EXCLUDED.drug_id,
                  description = EXCLUDED.description,
                  updated_at  = NOW()
RETURNING id, (xmax = 0) AS created
`

type UpsertPackageParams struct {
	DrugID                   int64       `json:"drug_id"`
	Description              string      `json:"description"`
	PresentationRegistration pgtype.Text `json:"presentation_registration"`
}

type UpsertPackageRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

func (q *Queries) UpsertPackage(ctx context.Context, arg UpsertPackageParams) (UpsertPackageRow, error) {
	row := q.db.QueryRow(ctx, upsertPackage, arg.DrugID, arg.Description, arg.PresentationRegistration)
	var i UpsertPackageRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const upsertPackageEAN = `-- name: UpsertPackageEAN :one
INSERT INTO package_eans (package_id, ean)
VALUES ($1, $2)
ON CONFLICT (ean)
    DO UPDATE SET package_id = package_eans.package_id
RETURNING package_id, (xmax = 0) AS created
`

type UpsertPackageEANParams struct {
	PackageID int64  `json:"package_id"`
	Ean       string `json:"ean"`
}

type UpsertPackageEANRow struct {
	PackageID int64 `json:"package_id"`
	Created   bool  `json:"created"`
}

// The DO UPDATE keeps the current owner on purpose: the caller compares the
// returned package_id with the expected one and reports an error when the EAN
// already belongs to another package.
func (q *Queries) UpsertPackageEAN(ctx context.Context, arg UpsertPackageEANParams) (UpsertPackageEANRow, error) {
	row := q.db.QueryRow(ctx, upsertPackageEAN, arg.PackageID, arg.Ean)
	var i UpsertPackageEANRow
	err := row.Scan(&i.PackageID, &i.Created)
	return i, err
}

const upsertSummary = `-- name: UpsertSummary :one
INSERT INTO summaries (drug_id,
                       what_is_it_for,
                       posology,
                       missed_dose,
                       warnings,
                       adverse_effects,
                       drug_interactions,
                       contraindications,
                       side_effects,
                       when_to_seek_help,
                       mechanism_of_action,
                       storage,
                       source_url,
                       leaflet_expedient,
                       leaflet_published_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (drug_id)
    DO UPDATE SET what_is_it_for       = EXCLUDED.what_is_it_for,
                  posology             = EXCLUDED.posology,
                  missed_dose          = EXCLUDED.missed_dose,
                  warnings             = EXCLUDED.warnings,
                  adverse_effects      = EXCLUDED.adverse_effects,
                  drug_interactions    = EXCLUDED.drug_interactions,
                  contraindications    = EXCLUDED.contraindications,
                  side_effects         = EXCLUDED.side_effects,
                  when_to_seek_help    = EXCLUDED.when_to_seek_help,
                  mechanism_of_action  = EXCLUDED.mechanism_of_action,
                  storage              = EXCLUDED.storage,
                  source_url           = EXCLUDED.source_url,
                  leaflet_expedient    = EXCLUDED.leaflet_expedient,
                  leaflet_published_at = EXCLUDED.leaflet_published_at,
                  reviewed_by          = NULL,
                  reviewed_by_user_id  = NULL,
                  reviewed_at          = NULL,
                  updated_at           = NOW()
RETURNING id, (xmax = 0) AS created
`

type UpsertSummaryParams struct {
	DrugID             int64       `json:"drug_id"`
	WhatIsItFor        string      `json:"what_is_it_for"`
	Posology           string      `json:"posology"`
	MissedDose         pgtype.Text `json:"missed_dose"`
	Warnings           pgtype.Text `json:"warnings"`
	AdverseEffects     pgtype.Text `json:"adverse_effects"`
	DrugInteractions   pgtype.Text `json:"drug_interactions"`
	Contraindications  pgtype.Text `json:"contraindications"`
	SideEffects        pgtype.Text `json:"side_effects"`
	WhenToSeekHelp     pgtype.Text `json:"when_to_seek_help"`
	MechanismOfAction  pgtype.Text `json:"mechanism_of_action"`
	Storage            pgtype.Text `json:"storage"`
	SourceUrl          string      `json:"source_url"`
	LeafletExpedient   pgtype.Text `json:"leaflet_expedient"`
	LeafletPublishedAt pgtype.Date `json:"leaflet_published_at"`
}

type UpsertSummaryRow struct {
	ID      int64 `json:"id"`
	Created bool  `json:"created"`
}

// Importing leaflet text clears the review, exactly like editing it in the panel.
func (q *Queries) UpsertSummary(ctx context.Context, arg UpsertSummaryParams) (UpsertSummaryRow, error) {
	row := q.db.QueryRow(ctx, upsertSummary,
		arg.DrugID,
		arg.WhatIsItFor,
		arg.Posology,
		arg.MissedDose,
		arg.Warnings,
		arg.AdverseEffects,
		arg.DrugInteractions,
		arg.Contraindications,
		arg.SideEffects,
		arg.WhenToSeekHelp,
		arg.MechanismOfAction,
		arg.Storage,
		arg.SourceUrl,
		arg.LeafletExpedient,
		arg.LeafletPublishedAt,
	)
	var i UpsertSummaryRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}
