// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDrugIngredientsNotIn = `-- name: DeleteDrugIngredientsNotIn :exec
DELETE
FROM drug_ingredients
WHERE drug_id = $1
  AND NOT (ingredient_id = ANY ($2::BIGINT[]))
`

type DeleteDrugIngredientsNotInParams struct {
	DrugID        int64   `json:"drug_id"`
	IngredientIds []int64 `json:"ingredient_ids"`
}

// Removes the links of a drug that are not in the new list of ingredients.
func (q *Queries) DeleteDrugIngredientsNotIn(ctx context.Context, arg DeleteDrugIngredientsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteDrugIngredientsNotIn, arg.DrugID, arg.IngredientIds)
	return err
}

const linkDrugIngredient = `-- name: LinkDrugIngredient :exec
INSERT INTO drug_ingredients (drug_id, ingredient_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkDrugIngredientParams struct {
	DrugID       int64 `json:"drug_id"`
	IngredientID int64 `json:"ingredient_id"`
}

func (q *Queries) LinkDrugIngredient(ctx context.Context, arg LinkDrugIngredientParams) error {
	_, err := q.db.Exec(ctx, linkDrugIngredient, arg.DrugID, arg.IngredientID)
	return err
}

const listDrugsByEANs = `-- name: ListDrugsByEANs :many
SELECT pe.ean,
       d.id AS drug_id,
       d.brand_name,
       d.manufacturer,
       COALESCE((SELECT array_agg(ai.name ORDER BY ai.name)
                 FROM drug_ingredients AS di
                          JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
                 WHERE di.drug_id = d.id), '{}')::TEXT[] AS active_ingredients
FROM package_eans AS pe
         JOIN packages AS p ON p.id = pe.package_id
         JOIN drugs AS d ON d.id = p.drug_id
WHERE pe.ean = ANY ($1::TEXT[])
`

type ListDrugsByEANsRow struct {
	Ean               string      `json:"ean"`
	DrugID            int64       `json:"drug_id"`
	BrandName         pgtype.Text `json:"brand_name"`
	Manufacturer      string      `json:"manufacturer"`
	ActiveIngredients []string    `json:"active_ingredients"`
}

// Resolves the scanned barcodes into drugs, with their active ingredients.
func (q *Queries) ListDrugsByEANs(ctx context.Context, eans []string) ([]ListDrugsByEANsRow, error) {
	rows, err := q.db.Query(ctx, listDrugsByEANs, eans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDrugsByEANsRow
	for rows.Next() {
		var i ListDrugsByEANsRow
		if err := rows.Scan(
			&i.Ean,
			&i.DrugID,
			&i.BrandName,
			&i.Manufacturer,
			&i.ActiveIngredients,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByDrugID = `-- name: ListIngredientsByDrugID :many
SELECT ai.id, ai.name
FROM drug_ingredients AS di
         JOIN active_ingredients AS ai ON ai.id = di.ingredient_id
WHERE di.drug_id = $1
ORDER BY ai.name
`

type ListIngredientsByDrugIDRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListIngredientsByDrugID(ctx context.Context, drugID int64) ([]ListIngredientsByDrugIDRow, error) {
	rows, err := q.db.Query(ctx, listIngredientsByDrugID, drugID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngredientsByDrugIDRow
	for rows.Next() {
		var i ListIngredientsByDrugIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredient = `-- name: UpsertIngredient :one
INSERT INTO active_ingredients (name)
VALUES ($1)
ON CONFLICT (normalized_name)
    DO UPDATE SET name = active_ingredients.name
RETURNING id
`

// Matching is by normalized_name (generated by the database), so "Dipirona Sódica",
// "dipirona sodica" and "dipirona  sódica" all land on the same row. The DO UPDATE
// is a no-op that exists only to make the statement return the id in both cases.
func (q *Queries) UpsertIngredient(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, upsertIngredient, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
