// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngredientInteractions = `-- name: CountIngredientInteractions :one
SELECT COUNT(*)
FROM ingredient_interactions
`

func (q *Queries) CountIngredientInteractions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countIngredientInteractions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteIngredientInteraction = `-- name: DeleteIngredientInteraction :execrows
DELETE
FROM ingredient_interactions
WHERE ingredient_a_id = LEAST($1::BIGINT, $2::BIGINT)
  AND ingredient_b_id = GREATEST($1::BIGINT, $2::BIGINT)
`

type DeleteIngredientInteractionParams struct {
	IngredientAID int64 `json:"ingredient_a_id"`
	IngredientBID int64 `json:"ingredient_b_id"`
}

func (q *Queries) DeleteIngredientInteraction(ctx context.Context, arg DeleteIngredientInteractionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIngredientInteraction, arg.IngredientAID, arg.IngredientBID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findInteractionsBetweenEANs = `-- name: FindInteractionsBetweenEANs :many
WITH scanned AS (SELECT DISTINCT d.id AS drug_id, di.ingredient_id
                 FROM package_eans AS pe
                          JOIN packages AS p ON p.id = pe.package_id
                          JOIN drugs AS d ON d.id = p.drug_id
                          JOIN drug_ingredients AS di ON di.drug_id = d.id
                 WHERE pe.ean = ANY ($1::TEXT[])),
     pairs AS (SELECT LEAST(x.ingredient_id, y.ingredient_id)    AS ingredient_a_id,
                      GREATEST(x.ingredient_id, y.ingredient_id) AS ingredient_b_id,
                      x.drug_id                                  AS drug_a_id,
                      y.drug_id                                  AS drug_b_id
               FROM scanned AS x
                        JOIN scanned AS y ON x.drug_id < y.drug_id)
SELECT DISTINCT a.name   AS ingredient_a,
                b.name   AS ingredient_b,
                ii.severity,
                ii.description,
                ii.recommendation,
                ii.source_url,
                pairs.drug_a_id,
                pairs.drug_b_id
FROM pairs
         JOIN ingredient_interactions AS ii
              ON ii.ingredient_a_id = pairs.ingredient_a_id
                  AND ii.ingredient_b_id = pairs.ingredient_b_id
         JOIN active_ingredients AS a ON a.id = ii.ingredient_a_id
         JOIN active_ingredients AS b ON b.id = ii.ingredient_b_id
ORDER BY ii.severity, a.name, b.name
`

type FindInteractionsBetweenEANsRow struct {
	IngredientA    string      `json:"ingredient_a"`
	IngredientB    string      `json:"ingredient_b"`
	Severity       string      `json:"severity"`
	Description    string      `json:"description"`
	Recommendation pgtype.Text `json:"recommendation"`
	SourceUrl      string      `json:"source_url"`
	DrugAID        int64       `json:"drug_a_id"`
	DrugBID        int64       `json:"drug_b_id"`
}

// The check the app calls: every pair of active ingredients coming from
// DIFFERENT boxes is compared against the rules.
//
//	scanned -> one row per (drug, ingredient) behind the scanned barcodes
//	pairs   -> every combination of ingredients from two different drugs
//
// The combination inside a single drug is left out on purpose: that mix is
// already approved by Anvisa.
func (q *Queries) FindInteractionsBetweenEANs(ctx context.Context, eans []string) ([]FindInteractionsBetweenEANsRow, error) {
	rows, err := q.db.Query(ctx, findInteractionsBetweenEANs, eans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindInteractionsBetweenEANsRow
	for rows.Next() {
		var i FindInteractionsBetweenEANsRow
		if err := rows.Scan(
			&i.IngredientA,
			&i.IngredientB,
			&i.Severity,
			&i.Description,
			&i.Recommendation,
			&i.SourceUrl,
			&i.DrugAID,
			&i.DrugBID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientInteractions = `-- name: ListIngredientInteractions :many
SELECT ii.ingredient_a_id,
       a.name AS ingredient_a,
       ii.ingredient_b_id,
       b.name AS ingredient_b,
       ii.severity,
       ii.description,
       ii.recommendation,
       ii.source_url,
       ii.updated_at
FROM ingredient_interactions AS ii
         JOIN active_ingredients AS a ON a.id = ii.ingredient_a_id
         JOIN active_ingredients AS b ON b.id = ii.ingredient_b_id
ORDER BY a.name, b.name LIMIT $1
OFFSET $2
`

type ListIngredientInteractionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListIngredientInteractionsRow struct {
	IngredientAID  int64              `json:"ingredient_a_id"`
	IngredientA    string             `json:"ingredient_a"`
	IngredientBID  int64              `json:"ingredient_b_id"`
	IngredientB    string             `json:"ingredient_b"`
	Severity       string             `json:"severity"`
	Description    string             `json:"description"`
	Recommendation pgtype.Text        `json:"recommendation"`
	SourceUrl      string             `json:"source_url"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListIngredientInteractions(ctx context.Context, arg ListIngredientInteractionsParams) ([]ListIngredientInteractionsRow, error) {
	rows, err := q.db.Query(ctx, listIngredientInteractions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIngredientInteractionsRow
	for rows.Next() {
		var i ListIngredientInteractionsRow
		if err := rows.Scan(
			&i.IngredientAID,
			&i.IngredientA,
			&i.IngredientBID,
			&i.IngredientB,
			&i.Severity,
			&i.Description,
			&i.Recommendation,
			&i.SourceUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIngredientInteraction = `-- name: UpsertIngredientInteraction :one

INSERT INTO ingredient_interactions (ingredient_a_id, ingredient_b_id, severity, description, recommendation, source_url)
VALUES (LEAST($1::BIGINT, $2::BIGINT),
        GREATEST($1::BIGINT, $2::BIGINT),
        $3, $4, $5, $6)
ON CONFLICT (ingredient_a_id, ingredient_b_id)
    DO UPDATE SET severity       = EXCLUDED.severity,
                  description    = EXCLUDED.description,
                  recommendation = EXCLUDED.recommendation,
                  source_url     = EXCLUDED.source_url,
                  updated_at     = NOW()
RETURNING ingredient_a_id, ingredient_b_id, (xmax = 0) AS created
`

type UpsertIngredientInteractionParams struct {
	IngredientAID  int64       `json:"ingredient_a_id"`
	IngredientBID  int64       `json:"ingredient_b_id"`
	Severity       string      `json:"severity"`
	Description    string      `json:"description"`
	Recommendation pgtype.Text `json:"recommendation"`
	SourceUrl      string      `json:"source_url"`
}

type UpsertIngredientInteractionRow struct {
	IngredientAID int64 `json:"ingredient_a_id"`
	IngredientBID int64 `json:"ingredient_b_id"`
	Created       bool  `json:"created"`
}

// Rules about what happens when two active ingredients are taken together.
// Pairs are always stored with the smaller id first (chk_pair_order), so every
// query here orders the ids with LEAST/GREATEST before touching the table.
func (q *Queries) UpsertIngredientInteraction(ctx context.Context, arg UpsertIngredientInteractionParams) (UpsertIngredientInteractionRow, error) {
	row := q.db.QueryRow(ctx, upsertIngredientInteraction,
		arg.IngredientAID,
		arg.IngredientBID,
		arg.Severity,
		arg.Description,
		arg.Recommendation,
		arg.SourceUrl,
	)
	var i UpsertIngredientInteractionRow
	err := row.Scan(&i.IngredientAID, &i.IngredientBID, &i.Created)
	return i, err
}
