// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Drug struct {
	ID                 int64
	RegistrationNumber string
	BrandName          pgtype.Text
	ActiveIngredient   string
	Manufacturer       string
	CreatedAt          pgtype.Timestamptz
}

type Package struct {
	ID          int64
	DrugID      int64
	Ean         string
	Description string
	CreatedAt   pgtype.Timestamptz
}
