// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Drug struct {
	ID                 int64              `json:"id"`
	RegistrationNumber string             `json:"registration_number"`
	BrandName          pgtype.Text        `json:"brand_name"`
	ActiveIngredient   string             `json:"active_ingredient"`
	Manufacturer       string             `json:"manufacturer"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Package struct {
	ID          int64              `json:"id"`
	DrugID      int64              `json:"drug_id"`
	Ean         string             `json:"ean"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
