// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Drug struct {
	ID                 int64              `json:"id"`
	RegistrationNumber string             `json:"registration_number"`
	BrandName          pgtype.Text        `json:"brand_name"`
	ActiveIngredient   string             `json:"active_ingredient"`
	Manufacturer       string             `json:"manufacturer"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Package struct {
	ID          int64              `json:"id"`
	DrugID      int64              `json:"drug_id"`
	Ean         string             `json:"ean"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Summary struct {
	ID                int64              `json:"id"`
	DrugID            int64              `json:"drug_id"`
	WhatIsItFor       string             `json:"what_is_it_for"`
	Posology          string             `json:"posology"`
	AdverseEffects    pgtype.Text        `json:"adverse_effects"`
	DrugInteractions  pgtype.Text        `json:"drug_interactions"`
	Contraindications pgtype.Text        `json:"contraindications"`
	SideEffects       pgtype.Text        `json:"side_effects"`
	WhenToSeekHelp    pgtype.Text        `json:"when_to_seek_help"`
	MechanismOfAction pgtype.Text        `json:"mechanism_of_action"`
	Storage           pgtype.Text        `json:"storage"`
	SourceUrl         string             `json:"source_url"`
	ReviewedBy        pgtype.Text        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
