// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package db

import (
	"context"
)

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (drug_id, ean, description)
SELECT d.id, $2, $3
FROM drugs d
WHERE d.registration_number = $1
    RETURNING id
`

type CreatePackageParams struct {
	RegistrationNumber string `json:"registration_number"`
	Ean                string `json:"ean"`
	Description        string `json:"description"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPackage, arg.RegistrationNumber, arg.Ean, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}
