// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPackage = `-- name: CreatePackage :one
WITH new_package AS (
    INSERT INTO packages (drug_id, description, presentation_registration)
        SELECT d.id, $1::text, $2::varchar
        FROM drugs AS d
        WHERE d.registration_number = $3::varchar
        RETURNING id),
     new_eans AS (
         INSERT INTO package_eans (package_id, ean)
             SELECT np.id, e.ean
             FROM new_package AS np,
                  unnest($4::text[]) AS e(ean))
SELECT id
FROM new_package
`

type CreatePackageParams struct {
	Description              string      `json:"description"`
	PresentationRegistration pgtype.Text `json:"presentation_registration"`
	RegistrationNumber       string      `json:"registration_number"`
	Eans                     []string    `json:"eans"`
}

// Creates the package and its EANs in a single (atomic) statement: if an EAN
// already exists, nothing is written. If no drug has this registration_number,
// no row is returned (pgx.ErrNoRows).
func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.Description,
		arg.PresentationRegistration,
		arg.RegistrationNumber,
		arg.Eans,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePackage = `-- name: DeletePackage :execrows
DELETE
FROM packages
WHERE id = $1
`

func (q *Queries) DeletePackage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPackageById = `-- name: GetPackageById :one
SELECT p.id,
       p.drug_id,
       p.description,
       p.presentation_registration,
       COALESCE(array_agg(pe.ean ORDER BY pe.ean) FILTER (WHERE pe.ean IS NOT NULL), '{}')::text[] AS eans,
       p.updated_at
FROM packages AS p
         LEFT JOIN package_eans AS pe ON pe.package_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type GetPackageByIdRow struct {
	ID                       int64              `json:"id"`
	DrugID                   int64              `json:"drug_id"`
	Description              string             `json:"description"`
	PresentationRegistration pgtype.Text        `json:"presentation_registration"`
	Eans                     []string           `json:"eans"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPackageById(ctx context.Context, id int64) (GetPackageByIdRow, error) {
	row := q.db.QueryRow(ctx, getPackageById, id)
	var i GetPackageByIdRow
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.Description,
		&i.PresentationRegistration,
		&i.Eans,
		&i.UpdatedAt,
	)
	return i, err
}

const listPackages = `-- name: ListPackages :many
SELECT p.id,
       p.drug_id,
       p.description,
       p.presentation_registration,
       COALESCE(array_agg(pe.ean ORDER BY pe.ean) FILTER (WHERE pe.ean IS NOT NULL), '{}')::text[] AS eans,
       p.updated_at
FROM packages AS p
         LEFT JOIN package_eans AS pe ON pe.package_id = p.id
GROUP BY p.id
ORDER BY p.id LIMIT $1
OFFSET $2
`

type ListPackagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPackagesRow struct {
	ID                       int64              `json:"id"`
	DrugID                   int64              `json:"drug_id"`
	Description              string             `json:"description"`
	PresentationRegistration pgtype.Text        `json:"presentation_registration"`
	Eans                     []string           `json:"eans"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPackages(ctx context.Context, arg ListPackagesParams) ([]ListPackagesRow, error) {
	rows, err := q.db.Query(ctx, listPackages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagesRow
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.DrugID,
			&i.Description,
			&i.PresentationRegistration,
			&i.Eans,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByDrugID = `-- name: ListPackagesByDrugID :many
SELECT p.id,
       p.drug_id,
       p.description,
       p.presentation_registration,
       COALESCE(array_agg(pe.ean ORDER BY pe.ean) FILTER (WHERE pe.ean IS NOT NULL), '{}')::text[] AS eans,
       p.updated_at
FROM packages AS p
         LEFT JOIN package_eans AS pe ON pe.package_id = p.id
WHERE p.drug_id = $1
GROUP BY p.id
ORDER BY p.id LIMIT $2
OFFSET $3
`

type ListPackagesByDrugIDParams struct {
	DrugID int64 `json:"drug_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPackagesByDrugIDRow struct {
	ID                       int64              `json:"id"`
	DrugID                   int64              `json:"drug_id"`
	Description              string             `json:"description"`
	PresentationRegistration pgtype.Text        `json:"presentation_registration"`
	Eans                     []string           `json:"eans"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPackagesByDrugID(ctx context.Context, arg ListPackagesByDrugIDParams) ([]ListPackagesByDrugIDRow, error) {
	rows, err := q.db.Query(ctx, listPackagesByDrugID, arg.DrugID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagesByDrugIDRow
	for rows.Next() {
		var i ListPackagesByDrugIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DrugID,
			&i.Description,
			&i.PresentationRegistration,
			&i.Eans,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackage = `-- name: UpdatePackage :execrows
WITH updated AS (
    UPDATE packages AS p
        SET drug_id = $1,
            description = $2,
            presentation_registration = $3,
            updated_at = NOW()
        WHERE p.id = $4
        RETURNING p.id),
     removed_eans AS (
         DELETE FROM package_eans AS pe
             USING updated AS u
             WHERE pe.package_id = u.id
                 AND NOT (pe.ean = ANY ($5::text[]))),
     added_eans AS (
         INSERT INTO package_eans (package_id, ean)
             SELECT u.id, e.ean
             FROM updated AS u,
                  unnest($5::text[]) AS e(ean)
             WHERE NOT EXISTS (SELECT 1
                               FROM package_eans AS x
                               WHERE x.package_id = u.id
                                 AND x.ean = e.ean))
SELECT id
FROM updated
`

type UpdatePackageParams struct {
	DrugID                   int64       `json:"drug_id"`
	Description              string      `json:"description"`
	PresentationRegistration pgtype.Text `json:"presentation_registration"`
	ID                       int64       `json:"id"`
	Eans                     []string    `json:"eans"`
}

// Updates the package and syncs its EAN list: removes the ones no longer in
// the list and inserts the new ones, all in a single statement.
func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePackage,
		arg.DrugID,
		arg.Description,
		arg.PresentationRegistration,
		arg.ID,
		arg.Eans,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
