// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (drug_id,
                       what_is_it_for,
                       posology,
                       adverse_effects,
                       drug_interactions,
                       contraindications,
                       side_effects,
                       when_to_seek_help,
                       mechanism_of_action,
                       storage,
                       source_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id
`

type CreateSummaryParams struct {
	DrugID            int64       `json:"drug_id"`
	WhatIsItFor       string      `json:"what_is_it_for"`
	Posology          string      `json:"posology"`
	AdverseEffects    pgtype.Text `json:"adverse_effects"`
	DrugInteractions  pgtype.Text `json:"drug_interactions"`
	Contraindications pgtype.Text `json:"contraindications"`
	SideEffects       pgtype.Text `json:"side_effects"`
	WhenToSeekHelp    pgtype.Text `json:"when_to_seek_help"`
	MechanismOfAction pgtype.Text `json:"mechanism_of_action"`
	Storage           pgtype.Text `json:"storage"`
	SourceUrl         string      `json:"source_url"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.DrugID,
		arg.WhatIsItFor,
		arg.Posology,
		arg.AdverseEffects,
		arg.DrugInteractions,
		arg.Contraindications,
		arg.SideEffects,
		arg.WhenToSeekHelp,
		arg.MechanismOfAction,
		arg.Storage,
		arg.SourceUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSummary = `-- name: DeleteSummary :execrows
DELETE
FROM summaries
WHERE id = $1
`

func (q *Queries) DeleteSummary(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSummary, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSummaryByDrugID = `-- name: GetSummaryByDrugID :one
SELECT id,
       drug_id,
       what_is_it_for,
       posology,
       adverse_effects,
       drug_interactions,
       contraindications,
       side_effects,
       when_to_seek_help,
       mechanism_of_action,
       storage,
       source_url,
       reviewed_by,
       reviewed_at,
       updated_at
FROM summaries
WHERE drug_id = $1
`

type GetSummaryByDrugIDRow struct {
	ID                int64              `json:"id"`
	DrugID            int64              `json:"drug_id"`
	WhatIsItFor       string             `json:"what_is_it_for"`
	Posology          string             `json:"posology"`
	AdverseEffects    pgtype.Text        `json:"adverse_effects"`
	DrugInteractions  pgtype.Text        `json:"drug_interactions"`
	Contraindications pgtype.Text        `json:"contraindications"`
	SideEffects       pgtype.Text        `json:"side_effects"`
	WhenToSeekHelp    pgtype.Text        `json:"when_to_seek_help"`
	MechanismOfAction pgtype.Text        `json:"mechanism_of_action"`
	Storage           pgtype.Text        `json:"storage"`
	SourceUrl         string             `json:"source_url"`
	ReviewedBy        pgtype.Text        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSummaryByDrugID(ctx context.Context, drugID int64) (GetSummaryByDrugIDRow, error) {
	row := q.db.QueryRow(ctx, getSummaryByDrugID, drugID)
	var i GetSummaryByDrugIDRow
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.WhatIsItFor,
		&i.Posology,
		&i.AdverseEffects,
		&i.DrugInteractions,
		&i.Contraindications,
		&i.SideEffects,
		&i.WhenToSeekHelp,
		&i.MechanismOfAction,
		&i.Storage,
		&i.SourceUrl,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSummaryByID = `-- name: GetSummaryByID :one
SELECT id,
       drug_id,
       what_is_it_for,
       posology,
       adverse_effects,
       drug_interactions,
       contraindications,
       side_effects,
       when_to_seek_help,
       mechanism_of_action,
       storage,
       source_url,
       reviewed_by,
       reviewed_at,
       updated_at
FROM summaries
WHERE id = $1
`

type GetSummaryByIDRow struct {
	ID                int64              `json:"id"`
	DrugID            int64              `json:"drug_id"`
	WhatIsItFor       string             `json:"what_is_it_for"`
	Posology          string             `json:"posology"`
	AdverseEffects    pgtype.Text        `json:"adverse_effects"`
	DrugInteractions  pgtype.Text        `json:"drug_interactions"`
	Contraindications pgtype.Text        `json:"contraindications"`
	SideEffects       pgtype.Text        `json:"side_effects"`
	WhenToSeekHelp    pgtype.Text        `json:"when_to_seek_help"`
	MechanismOfAction pgtype.Text        `json:"mechanism_of_action"`
	Storage           pgtype.Text        `json:"storage"`
	SourceUrl         string             `json:"source_url"`
	ReviewedBy        pgtype.Text        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSummaryByID(ctx context.Context, id int64) (GetSummaryByIDRow, error) {
	row := q.db.QueryRow(ctx, getSummaryByID, id)
	var i GetSummaryByIDRow
	err := row.Scan(
		&i.ID,
		&i.DrugID,
		&i.WhatIsItFor,
		&i.Posology,
		&i.AdverseEffects,
		&i.DrugInteractions,
		&i.Contraindications,
		&i.SideEffects,
		&i.WhenToSeekHelp,
		&i.MechanismOfAction,
		&i.Storage,
		&i.SourceUrl,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSummaries = `-- name: ListSummaries :many
SELECT s.id,
       s.drug_id,
       d.brand_name,
       d.active_ingredient,
       s.what_is_it_for,
       s.source_url,
       s.reviewed_by,
       s.reviewed_at,
       s.updated_at
FROM summaries AS s
         INNER JOIN drugs AS d ON d.id = s.drug_id
ORDER BY d.brand_name NULLS FIRST LIMIT $1
OFFSET $2
`

type ListSummariesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSummariesRow struct {
	ID               int64              `json:"id"`
	DrugID           int64              `json:"drug_id"`
	BrandName        pgtype.Text        `json:"brand_name"`
	ActiveIngredient string             `json:"active_ingredient"`
	WhatIsItFor      string             `json:"what_is_it_for"`
	SourceUrl        string             `json:"source_url"`
	ReviewedBy       pgtype.Text        `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSummaries(ctx context.Context, arg ListSummariesParams) ([]ListSummariesRow, error) {
	rows, err := q.db.Query(ctx, listSummaries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummariesRow
	for rows.Next() {
		var i ListSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.DrugID,
			&i.BrandName,
			&i.ActiveIngredient,
			&i.WhatIsItFor,
			&i.SourceUrl,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewSummary = `-- name: ReviewSummary :execrows
UPDATE summaries
SET reviewed_by = $2,
    reviewed_at = NOW(),
    updated_at  = NOW()
WHERE id = $1
`

type ReviewSummaryParams struct {
	ID         int64       `json:"id"`
	ReviewedBy pgtype.Text `json:"reviewed_by"`
}

func (q *Queries) ReviewSummary(ctx context.Context, arg ReviewSummaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewSummary, arg.ID, arg.ReviewedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSummary = `-- name: UpdateSummary :execrows
UPDATE summaries
SET what_is_it_for      = $2,
    posology            = $3,
    adverse_effects     = $4,
    drug_interactions   = $5,
    contraindications   = $6,
    side_effects        = $7,
    when_to_seek_help   = $8,
    mechanism_of_action = $9,
    storage             = $10,
    source_url          = $11,
    updated_at          = NOW()
WHERE id = $1
`

type UpdateSummaryParams struct {
	ID                int64       `json:"id"`
	WhatIsItFor       string      `json:"what_is_it_for"`
	Posology          string      `json:"posology"`
	AdverseEffects    pgtype.Text `json:"adverse_effects"`
	DrugInteractions  pgtype.Text `json:"drug_interactions"`
	Contraindications pgtype.Text `json:"contraindications"`
	SideEffects       pgtype.Text `json:"side_effects"`
	WhenToSeekHelp    pgtype.Text `json:"when_to_seek_help"`
	MechanismOfAction pgtype.Text `json:"mechanism_of_action"`
	Storage           pgtype.Text `json:"storage"`
	SourceUrl         string      `json:"source_url"`
}

func (q *Queries) UpdateSummary(ctx context.Context, arg UpdateSummaryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSummary,
		arg.ID,
		arg.WhatIsItFor,
		arg.Posology,
		arg.AdverseEffects,
		arg.DrugInteractions,
		arg.Contraindications,
		arg.SideEffects,
		arg.WhenToSeekHelp,
		arg.MechanismOfAction,
		arg.Storage,
		arg.SourceUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
