server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # /api/drugs -> http://api:8080/drugs  (a barra no final do proxy_pass remove o prefixo /api)
    location /api/ {
        proxy_pass http://api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA: qualquer rota desconhecida cai no index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
